#!/usr/bin/env python3
"""Package only the shared reference sections needed by each standalone skill."""
import argparse
import re
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]
MARKER = '<!-- Generated by scripts/sync_references.py; do not edit. -->\n'


def slug(title):
    return re.sub(r'[^\w -]', '', title.lower()).replace(' ', '-')


def file_references(text):
    """Local Markdown dependencies, including the backtick notation used by skills."""
    links = re.findall(r'\]\(\s*(<[^>\n]+>|[^\s)]+)', text)
    links += re.findall(r'^ {0,3}\[[^\]\n]+\]:\s*(<[^>\n]+>|\S+)', text, re.M)
    code_paths = re.findall(r'`([^`\n]+\.md(?:#[^`\s]+)?)`', text)
    code_paths += re.findall(r'`((?:references/|scripts/|assets/)[^`\n]+)`', text)
    links += [path for path in code_paths if not path.startswith(('specs/', 'docs/specs/'))]
    for link in links:
        link = link.removeprefix('<').removesuffix('>')
        if re.match(r'^[a-z][a-z0-9+.-]*:', link, re.I) or link.startswith('//'):
            continue
        path, _, anchor = link.partition('#')
        yield unquote(path), unquote(anchor)


def sources(root):
    primer = (root / 'thinking-tools.md').read_text()
    parts = re.split(r'^## (.+)\n', primer, flags=re.M)
    result = {}
    for title, body in zip(parts[1::2], parts[2::2]):
        name = slug(title) + '.md'
        body = re.sub(r'\n---\s*$', '', body).strip()
        body = re.sub(r'\]\(#([\w-]+)\)', r'](\1.md)', body)
        body = re.sub(r'^(#{2,}) ', lambda m: m[1][1:] + ' ', body, flags=re.M)
        result[name] = (f'thinking-tools.md#{slug(title)}', f'# {title}\n\n{body}\n')
    for name in ('safety-floor.md', 'evidence-types.md'):
        text = (root / 'references' / name).read_text()
        text = re.sub(r'\.\./thinking-tools\.md#([\w-]+)', r'\1.md', text)
        result[name] = ('references/' + name, text)
    return result


def expected_references(root):
    canonical = sources(root)
    expected = {}
    for skill in sorted((root / 'skills').iterdir()):
        if not skill.is_dir():
            continue
        pending = []
        for path in skill.rglob('*.md'):
            text = path.read_text()
            if not text.startswith(MARKER):
                pending.extend(Path(ref).name for ref, _ in file_references(text))
        seen = set()
        while pending:
            name = pending.pop()
            if name in seen or name not in canonical:
                continue
            seen.add(name)
            origin, text = canonical[name]
            expected[skill / 'references' / name] = MARKER + f'<!-- Source: {origin} -->\n\n' + text
            pending.extend(Path(ref).name for ref, _ in file_references(text))
    return expected


def guarded(path, root):
    """True when no path component from path through root is a symlink."""
    current = path
    root_resolved = root.resolve()
    while True:
        if current.is_symlink():
            return False
        if current.exists() and current.resolve() == root_resolved:
            return True
        parent = current.parent
        if parent == current:
            return False
        current = parent


def sync(root, check=False):
    expected = expected_references(root)
    errors = []
    blocked = False
    writes = []
    for path, text in expected.items():
        if not guarded(path, root):
            errors.append(f'UNSAFE generated reference path: {path.relative_to(root)}')
            blocked = True
            continue
        if path.is_file() and not path.read_text().startswith(MARKER):
            errors.append(f'REFUSING to overwrite authored reference: {path.relative_to(root)}')
            blocked = True
            continue
        if not path.is_file() or path.read_text() != text:
            if check or blocked:
                errors.append(f'STALE OR MISSING generated reference: {path.relative_to(root)}')
            else:
                writes.append((path, text))
    unlinks = []
    for path in (root / 'skills').rglob('*.md'):
        if not path.is_file() or path.is_symlink() or not path.read_text().startswith(MARKER) or path in expected:
            continue
        if not guarded(path, root):
            errors.append(f'UNSAFE generated reference path: {path.relative_to(root)}')
            blocked = True
        elif check or blocked:
            errors.append(f'UNUSED generated reference: {path.relative_to(root)}')
        else:
            unlinks.append(path)
    if blocked:
        return errors
    for path, text in writes:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    for path in unlinks:
        path.unlink()
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail on missing or stale copies')
    args = parser.parse_args()
    try:
        errors = sync(ROOT, args.check)
    except (OSError, ValueError) as exc:
        errors = [str(exc)]
    for error in errors:
        print(error)
    if not errors:
        print('OK packaged references' if args.check else 'Updated packaged references')
    return bool(errors)


if __name__ == '__main__':
    raise SystemExit(main())
